const classNames = {
    pagingContainer:"mt-16 flex leading-6 font-medium",
    pagingCount:"",
    pagingNextBtn:"flex mr-8 transition-colors duration-200 hover:text-gray-900",
    pagingPrevBtn:"flex text-right ml-auto transition-colors duration-200 hover:text-gray-900",
    resultsGrid:"p-8 grid grid-cols-5 gap-4 bg-gray-100",
    searchResult:"px-0 shadow-md rounded-lg bg-white",
    searchResultImage:"rounded-t-lg min-w-full min-h-full bg-white",
    searchResultName:"text-center pb-4 pt-4 rounded-b-lg bg-white text-blue-400",
    searchResultLink:"",
    searchInput:"form-input px-4 py-3 rounded-lg w-max",
    searchBtn:"flex float-right ml-auto",
    searchForm:"",
    searchResultDetail:"p-8 grid grid-cols-3 bg-gray-100",
    searchResultDetailBio:"whitespace-pre-wrap text-grey-300",
    searchResultDetailImage:"w-64 h-64 rounded-lg",
    searchResultUsername:"",
    searchResultDetailLabel:"",
    searchResultDetailValue:"",
    searchResultDetailIcon:"",
    errorMessage:"w-full text-center text-red-500",
}
export default classNames;